version: "3"
services:
  db:
    image: mysql:8.0.19
    ports:
      - 3306:3306
    container_name: db
    environment:
      - MYSQL_DATABASE=sample
      - MYSQL_ROOT_PASSWORD=password
      - TZ="Asia/Tokyo"
